[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

# This automatically handles the proxy and routing from the root
[[redirects]]
  from = "/api/*"
  to = "https://kcn-attendance-2.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
